export default [
  {
    id: 1,
    extraInfo: "Sold out",
    image: "life-lessons.png",
    imageAlt: "Katie Zoferies by the pool",
    star: true,
    rating: 5.0,
    likes: 6,
    country: "USA",
    text: "Life lessons with Katie Zoferies",
    price: 136,
    unit: "person",
  },
  {
    id: 2,
    extraInfo: "Online",
    image: "wedding-photography.png",
    imageAlt: "Woman modelling a wedding dress",
    star: true,
    rating: 5.0,
    likes: 30,
    country: "USA",
    text: "Learn wedding photography",
    price: 125,
    unit: "person",
  },
  {
    id: 3,
    image: "mountain-bike.png",
    imageAlt: "Mountain bike with view",
    country: "USA",
    text: "Group mountain biking",
    price: 250,
    unit: "couple",
  },
]
